version: '2'
services:
  api:
    build: src/rest
    container_name: api
    #command: tail -F anything
    command: bash -c "cd /src && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    links:
      - mongo
    volumes:
      - ${ADBREW_CODEBASE_PATH}/tmp:/tmp
      - ${ADBREW_CODEBASE_PATH}/rest:/src
    depends_on:
      - mongo

  app:
    build: src/app/
    container_name: app
    #command: tail -F anything
    command: bash -c "cd /src && yarn install && yarn start"
    ports:
      - "3000:3000"
    volumes:
      - ${ADBREW_CODEBASE_PATH}/app:/src

  mongo:
    build:
      dockerfile: ./Dockerfile.mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${ADBREW_CODEBASE_PATH}/db/:/data/db
    command: /usr/bin/mongod --bind_ip 0.0.0.0

    